#############################################################################
# Generated by PAGE version 4.22
#  in conjunction with Tcl version 8.6
#  Apr 12, 2019 11:38:58 AM IST  platform: Linux
set vTcl(timestamp) ""


if {!$vTcl(borrow)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(active_menu_fg) #000000
}

#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top42
    global vTcl
    set base $vTcl(btop)
    if {$base == ""} {
        set base .top42
    }
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    namespace eval ::widgets_bindings {
        set tagslist {_TopLevel _vTclBalloon}
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.top42 {base} {
    if {$base == ""} {
        set base .top42
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m43" -background {#828282} -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 764x343+271+137
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1351 738
    wm minsize $top 1 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "CANCEL"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    label $top.lab62 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#4f4f4f} -font {-family {DejaVu Sans} -size 12} \
        -foreground {#ffffff} -highlightcolor black \
        -text {Do you want to cancel ?} 
    vTcl:DefineAlias "$top.lab62" "TIME_IN_FORCE_Label" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure TButton -background #d9d9d9
    ttk::style configure TButton -foreground #000000
    ttk::style configure TButton -font "TkDefaultFont"
    ttk::button $top.tBu69 \
        -takefocus {} -text OK 
    vTcl:DefineAlias "$top.tBu69" "OK_Button" vTcl:WidgetProc "Toplevel1" 1
    bind $top.tBu69 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Press to Submit}
    }
    ttk::style configure TButton -background #d9d9d9
    ttk::style configure TButton -foreground #000000
    ttk::style configure TButton -font "TkDefaultFont"
    ttk::button $top.tBu70 \
        -takefocus {} -text Cancel 
    vTcl:DefineAlias "$top.tBu70" "Cancel_Button" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.m43
    menu $site_3_0 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -font TkMenuFont -foreground {#000000} \
        -tearoff 0 
    ttk::style configure TButton -background #d9d9d9
    ttk::style configure TButton -foreground #000000
    ttk::style configure TButton -font "TkDefaultFont"
    ttk::button $top.tBu43 \
        -takefocus {} -text {Don't Cancel} 
    vTcl:DefineAlias "$top.tBu43" "Dont_cancel_button" vTcl:WidgetProc "Toplevel1" 1
    bind $top.tBu43 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Press to Submit}
    }
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab62 \
        -in $top -x 0 -y 100 -width 767 -relwidth 0 -height 23 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tBu69 \
        -in $top -x 240 -y 200 -width 101 -height 30 -anchor nw \
        -bordermode ignore 
    place $top.tBu70 \
        -in $top -x 410 -y 300 -rely 0.892 -width 101 -height 30 -anchor nw \
        -bordermode ignore 
    place $top.tBu43 \
        -in $top -x 420 -y 200 -width 101 -height 30 -anchor nw \
        -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top42 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

