#############################################################################
# Generated by PAGE version 4.22
#  in conjunction with Tcl version 8.6
#  Apr 12, 2019 11:30:10 AM IST  platform: Linux
set vTcl(timestamp) ""


if {!$vTcl(borrow)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(active_menu_fg) #000000
}

#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top42
    global vTcl
    set base $vTcl(btop)
    if {$base == ""} {
        set base .top42
    }
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    namespace eval ::widgets_bindings {
        set tagslist {_TopLevel _vTclBalloon}
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.top42 {base} {
    if {$base == ""} {
        set base .top42
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m43" -background {#b2b2b2} -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 764x462+271+137
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1351 738
    wm minsize $top 1 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "MODIFY"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    entry $top.ent43 \
        -background white -font TkFixedFont -foreground {#000000} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$top.ent43" "Entry1" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent44 \
        -background white -font TkFixedFont -foreground {#000000} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$top.ent44" "Entry1_1" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent45 \
        -background white -font TkFixedFont -foreground {#000000} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$top.ent45" "Entry1_2" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent46 \
        -background white -font TkFixedFont -foreground {#000000} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$top.ent46" "Entry1_1" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent47 \
        -background white -font TkFixedFont -foreground {#000000} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$top.ent47" "Entry1_3" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent48 \
        -background white -font TkFixedFont -foreground {#000000} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$top.ent48" "Entry1_4" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab49 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#4f4f4f} -font TkDefaultFont -foreground {#ffffff} \
        -highlightcolor black -text Symbol -width 196 
    vTcl:DefineAlias "$top.lab49" "Symbol_Label" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab50 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#4f4f4f} -font TkDefaultFont -foreground {#ffffff} \
        -highlightcolor black -text Size 
    vTcl:DefineAlias "$top.lab50" "Size_Label" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab51 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#4f4f4f} -font TkDefaultFont -foreground {#ffffff} \
        -highlightcolor black -text Client 
    vTcl:DefineAlias "$top.lab51" "Client_Label" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab52 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#4f4f4f} -font TkDefaultFont -foreground {#ffffff} \
        -highlightcolor black -text Exchange 
    vTcl:DefineAlias "$top.lab52" "Exchange_Label" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab53 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#4f4f4f} -font TkDefaultFont -foreground {#ffffff} \
        -highlightcolor black -text {Counter Party} 
    vTcl:DefineAlias "$top.lab53" "Counter_Party_Label" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab54 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#4f4f4f} -font TkDefaultFont -foreground {#ffffff} \
        -highlightcolor black -text TIF 
    vTcl:DefineAlias "$top.lab54" "TIF_Label" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent55 \
        -background white -font TkFixedFont -foreground {#000000} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black -width 196 
    vTcl:DefineAlias "$top.ent55" "Entry2" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent56 \
        -background white -font TkFixedFont -foreground {#000000} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$top.ent56" "Entry3" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent57 \
        -background white -font TkFixedFont -foreground {#000000} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$top.ent57" "Entry4" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent58 \
        -background white -font TkFixedFont -foreground {#000000} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$top.ent58" "Entry5" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent59 \
        -background white -font TkFixedFont -foreground {#000000} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$top.ent59" "Entry6" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent60 \
        -background white -font TkFixedFont -foreground {#000000} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$top.ent60" "Entry7" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab62 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#4f4f4f} -font {-family {DejaVu Sans} -size 12} \
        -foreground {#ffffff} -highlightcolor black -text {TIME IN FORCE} 
    vTcl:DefineAlias "$top.lab62" "TIME_IN_FORCE_Label" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab63 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#4f4f4f} -font TkDefaultFont -foreground {#ffffff} \
        -highlightcolor black -text { Symbol Description} 
    vTcl:DefineAlias "$top.lab63" " Symbol Description_Label" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab64 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#4f4f4f} -font TkDefaultFont -foreground {#ffffff} \
        -highlightcolor black -text {Price Instruction} 
    vTcl:DefineAlias "$top.lab64" "Price Instruction_Label" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab65 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#4f4f4f} -font TkDefaultFont -foreground {#ffffff} \
        -highlightcolor black -text {Client Description} 
    vTcl:DefineAlias "$top.lab65" "Client_Description_Label" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab66 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#4f4f4f} -font TkDefaultFont -foreground {#ffffff} \
        -highlightcolor black -text Account 
    vTcl:DefineAlias "$top.lab66" "Account_Label" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab67 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#4f4f4f} -font TkDefaultFont -foreground {#ffffff} \
        -highlightcolor black -text {TIF Date} 
    vTcl:DefineAlias "$top.lab67" "TIF_Date_Label" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab68 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#4f4f4f} -font TkDefaultFont -foreground {#ffffff} \
        -highlightcolor black -text Limit 
    vTcl:DefineAlias "$top.lab68" "Limit_Label" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure TButton -background #d9d9d9
    ttk::style configure TButton -foreground #000000
    ttk::style configure TButton -font "TkDefaultFont"
    ttk::button $top.tBu69 \
        -takefocus {} -text OK 
    vTcl:DefineAlias "$top.tBu69" "OK_Button" vTcl:WidgetProc "Toplevel1" 1
    bind $top.tBu69 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Press to Submit}
    }
    ttk::style configure TButton -background #d9d9d9
    ttk::style configure TButton -foreground #000000
    ttk::style configure TButton -font "TkDefaultFont"
    ttk::button $top.tBu70 \
        -takefocus {} -text Cancel 
    vTcl:DefineAlias "$top.tBu70" "Cancel_Button" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.m43
    menu $site_3_0 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -font TkMenuFont -foreground {#000000} \
        -tearoff 0 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.ent43 \
        -in $top -x 30 -y 40 -width 196 -relwidth 0 -height 25 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.ent44 \
        -in $top -x 30 -y 140 -width 196 -relwidth 0 -height 25 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.ent45 \
        -in $top -x 30 -y 90 -width 196 -relwidth 0 -height 25 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.ent46 \
        -in $top -x 30 -y 260 -width 196 -relwidth 0 -height 25 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.ent47 \
        -in $top -x 30 -y 195 -width 196 -relwidth 0 -height 25 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.ent48 \
        -in $top -x 30 -y 351 -width 196 -relwidth 0 -height 25 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab49 \
        -in $top -x 30 -y 20 -width 196 -relwidth 0 -height 20 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab50 \
        -in $top -x 30 -y 70 -width 196 -relwidth 0 -height 20 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab51 \
        -in $top -x 31 -y 120 -width 196 -relwidth 0 -height 20 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab52 \
        -in $top -x 30 -y 175 -width 196 -relwidth 0 -height 20 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab53 \
        -in $top -x 30 -y 240 -width 196 -relwidth 0 -height 20 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab54 \
        -in $top -x 30 -y 337 -width 196 -relwidth 0 -height 16 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.ent55 \
        -in $top -x 350 -y 38 -width 196 -relwidth 0 -height 25 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.ent56 \
        -in $top -x 349 -y 90 -width 196 -relwidth 0 -height 25 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.ent57 \
        -in $top -x 600 -y 88 -width 146 -relwidth 0 -height 25 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.ent58 \
        -in $top -x 347 -y 141 -width 196 -relwidth 0 -height 25 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.ent59 \
        -in $top -x 347 -y 194 -width 196 -relwidth 0 -height 25 -anchor nw \
        -bordermode ignore 
    place $top.ent60 \
        -in $top -x 347 -y 353 -width 336 -relwidth 0 -height 25 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab62 \
        -in $top -x 0 -y 302 -width 767 -relwidth 0 -height 23 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab63 \
        -in $top -x 350 -y 20 -width 196 -relwidth 0 -height 20 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab64 \
        -in $top -x 349 -y 75 -width 196 -relwidth 0 -height 20 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab65 \
        -in $top -x 347 -y 120 -width 196 -relwidth 0 -height 20 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab66 \
        -in $top -x 348 -y 173 -width 196 -relwidth 0 -height 20 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab67 \
        -in $top -x 347 -y 333 -width 336 -relwidth 0 -height 20 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab68 \
        -in $top -x 601 -y 68 -width 146 -relwidth 0 -height 20 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tBu69 \
        -in $top -x 240 -y 412 -width 101 -height 30 -anchor nw \
        -bordermode ignore 
    place $top.tBu70 \
        -in $top -x 410 -y 0 -rely 0.892 -width 101 -height 30 -anchor nw \
        -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top42 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

